#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  May 09, 2023 07:40:45 PM PDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+677+442
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "tomatoChat GUI"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    listbox "$top.lis47" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -height 422 -width 604 
    $top.lis47 configure -font "TkFixedFont"
    $top.lis47 insert end text
    vTcl:DefineAlias "$top.lis47" "msgbox" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    entry "$top.ent48" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 514 
    vTcl:DefineAlias "$top.ent48" "msgentry" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$top.tBu49" \
        -command "sendmsg" -takefocus {} -text "Send" -compound left 
    vTcl:DefineAlias "$top.tBu49" "sendmsg" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lis47 \
        -in $top -x 0 -y 0 -width 604 -relwidth 0 -height 422 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -y 420 -width 514 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 530 -y 420 -width 66 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 200x128+641+167
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "tomatoChat GUI Connection Window"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::label "$top.tLa52" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "TkDefaultFont" -relief flat -anchor w -justify left \
        -text "IP Address:" -compound left 
    vTcl:DefineAlias "$top.tLa52" "ipentrylabel" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ttk::label "$top.tLa53" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "TkDefaultFont" -relief flat -anchor w -justify left \
        -text "Port:" -compound left 
    vTcl:DefineAlias "$top.tLa53" "portentrylabel" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ttk::entry "$top.tEn54" \
        -font "TkTextFont" -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$top.tEn54" "ipentry" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ttk::label "$top.tLa55" \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font "TkDefaultFont" -relief flat -anchor w -justify left \
        -text "Username:" -compound left 
    vTcl:DefineAlias "$top.tLa55" "usernameenterylabel" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ttk::entry "$top.tEn56" \
        -font "TkTextFont" -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$top.tEn56" "portentry" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button "$top.tBu57" \
        -command "connect_to_server" -takefocus {} -text "Connect" \
        -compound left 
    vTcl:DefineAlias "$top.tBu57" "connect" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ttk::entry "$top.tEn58" \
        -font "TkTextFont" -foreground {} -background {} -takefocus {} \
        -cursor ibeam 
    vTcl:DefineAlias "$top.tEn58" "usernameentry" vTcl:WidgetProc "Toplevel2" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa52 \
        -in $top -x 0 -y 0 -rely 0.078 -width 0 -relwidth 0.46 -height 0 \
        -relheight 0.195 -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 0 -y 0 -rely 0.234 -width 0 -relwidth 0.435 -height 0 \
        -relheight 0.195 -anchor nw -bordermode ignore 
    place $top.tEn54 \
        -in $top -x 0 -relx 0.45 -y 0 -rely 0.078 -width 86 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa55 \
        -in $top -x 0 -y 0 -rely 0.391 -width 0 -relwidth 0.43 -height 0 \
        -relheight 0.203 -anchor nw -bordermode ignore 
    place $top.tEn56 \
        -in $top -x 0 -relx 0.45 -y 0 -rely 0.234 -width 86 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu57 \
        -in $top -x 0 -relx 0.3 -y 0 -rely 0.625 -width 76 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tEn58 \
        -in $top -x 0 -relx 0.45 -y 0 -rely 0.391 -width 86 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}

