#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    May 09, 2023 07:40:55 PM PDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import socket
import random
from threading import Thread
from datetime import datetime

import tomatochatgui

_debug = True # False to eliminate debug printing from callback functions.
msgcount = 0
s = socket.socket()

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = tomatochatgui.Toplevel1(_top1)
    # Creates a toplevel widget.
    global _top2, _w2
    _top2 = tk.Toplevel(root)
    _w2 = tomatochatgui.Toplevel2(_top2)
    root.mainloop()

def connect_to_server(*args):
    if _debug:
        print('tomatochatgui_support.connect_to_server')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
    s.connect((ip_input, port_input))

def sendmsg(*args):
    if _debug:
        print('tomatochatgui_support.sendmsg')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        s.send(msginput.encode())

def listen_for_messages():
    while True:
        msgcount += 1
        message = s.recv(1024).decode()
        listbox.insert(msgcount, message)
t = Thread(target=listen_for_messages)
t.daemon = True
t.start()

if __name__ == '__main__':
    tomatochatgui.start_up()




